# Deployment options for node.js in Google App Engine
runtime: nodejs
vm: true
threadsafe: true

skip_files:
  - ^(.*/)?.*/node_modules/.*$
  - ^(.*/)?.*/data/info.*\.db$

manual_scaling:
    instances: 1

env_variables:
  IN_GAE: 'true'
  NODE_ENV: 'production'
